import {
  ArrowLeft,
  ArrowRight,
  Baby,
  BadgeIndianRupee,
  Banknote,
  Bomb,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  CreditCard,
  Disc3,
  Download,
  Eye,
  EyeOff,
  Factory,
  FireExtinguisher,
  Flame,
  Flower,
  Flower2,
  Gift,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Link,
  List,
  ListChecks,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Minus,
  Moon,
  Orbit,
  Package,
  PartyPopper,
  Pencil,
  Phone,
  Plus,
  Rainbow,
  Rocket,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Trash2,
  Trophy,
  Truck,
  User,
  Worm,
  X,
  Zap,
} from 'lucide-react';

// Keys use the kebab-case names shown on https://lucide.dev/icons/
const registry = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  baby: Baby,
  'badge-indian-rupee': BadgeIndianRupee,
  banknote: Banknote,
  bomb: Bomb,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  clock: Clock,
  'credit-card': CreditCard,
  'disc-3': Disc3,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  factory: Factory,
  'fire-extinguisher': FireExtinguisher,
  flame: Flame,
  flower: Flower,
  'flower-2': Flower2,
  gift: Gift,
  landmark: Landmark,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  leaf: Leaf,
  link: Link,
  list: List,
  'list-checks': ListChecks,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  minus: Minus,
  moon: Moon,
  orbit: Orbit,
  package: Package,
  'party-popper': PartyPopper,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  rainbow: Rainbow,
  rocket: Rocket,
  search: Search,
  settings: Settings,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  'trash-2': Trash2,
  trophy: Trophy,
  truck: Truck,
  user: User,
  worm: Worm,
  x: X,
  zap: Zap,
};

export default function Icon({ name, size = 20, strokeWidth = 2, className = '', ...rest }) {
  const LucideIcon = registry[name];
  if (!LucideIcon) {
    if (import.meta.env.DEV) console.warn(`Icon "${name}" is not registered in Icons.jsx`);
    return null;
  }
  return (
    <LucideIcon
      size={size}
      strokeWidth={strokeWidth}
      className={`icon ${className}`.trim()}
      aria-hidden="true"
      focusable="false"
      {...rest}
    />
  );
}
